openapi: 3.0.0
info:
  title: A guide to exercise and nutrition
  description:
    TBA
  version: 3.0.0
servers:
  - url: http://127.0.0.1:8080/exercise-and-nutrition-api/v3

paths:
  /exercises:
    get:
      summary: Get a list of all exercises
      operationId: controller.get_exercises
      parameters:
        - name: target
          in: query
          required: false
          schema:
            type: string
        - name: LIMIT
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
        - name: RANDOM
          in: query
          required: false
          schema:
            type: boolean
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Exercise'

  /exercises/body_part/{bodyPart}:
    get:
      summary: Get exercises for a specific body part
      operationId: controller.get_exercises_by_body_part
      parameters:
        - name: bodyPart
          in: path
          required: true
          schema:
            type: string
        - name: LIMIT
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
        - name: RANDOM
          in: query
          required: false
          schema:
            type: boolean
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Exercise'

  /exercises/target/{target}:
    get:
      summary: Get exercises for a specific target
      operationId: controller.get_exercises_by_target
      parameters:
        - name: target
          in: path
          required: true
          schema:
            type: string
        - name: LIMIT
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
        - name: RANDOM
          in: query
          required: false
          schema:
            type: boolean
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Exercise'


  /foods:
    get:
      summary: Get a list of all foods
      operationId: controller.get_foods
      parameters:
        - name: diet
          in: query
          required: false
          schema:
            type: string
        - name: meal_type
          in: query
          required: false
          schema:
            type: string
        - name: LIMIT
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
        - name: RANDOM
          in: query
          required: false
          schema:
            type: boolean
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Food'


  /foods/diet/{diet}:
    get:
      summary: Get foods for a specific diet
      operationId: controller.get_foods_by_diet
      parameters:
        - name: diet
          in: path
          required: true
          schema:
            type: string
        - name: LIMIT
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
        - name: RANDOM
          in: query
          required: false
          schema:
            type: boolean
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Food'

  /foods/meal_type/{mealType}:
    get:
      summary: Get foods for a specific meal type
      operationId: controller.get_foods_by_meal_type
      parameters:
        - name: mealType
          in: path
          required: true
          schema:
            type: string
        - name: LIMIT
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
        - name: RANDOM
          in: query
          required: false
          schema:
            type: boolean
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Food'

components:
  schemas:
    Exercise:
      type: object
      properties:
        name:
          type: string
        body_part:
          type: string
        equipment:
          type: string
        target:
          type: string
        instructions:
          type: string

    Food:
      type: object
      properties:
        name:
          type: string
        diet:
          type: string
        meal_type:
          type: string
        cal:
          type: number
        fat:
          type: number
        carb:
          type: number
        protein:
          type: number